### PR TITLE
Fix incorrect offset when replacing empty lines

### PR DESCRIPTION
**Pull request by MatusGoljerSalesChamp**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
What is this?

**Comment by MatusGoljerSalesChamp** [comment]
We forked this repo and I accidentaly opened PR here instead of the fork (github automatically makes the "parent" repo default).  Sorry about the noise :) We'll probably detach the repo so this won't happen anymore.

**Comment by TomasVotruba** [comment]
Thanks for info. I don't even know where this repository came :D 

Do you want me to to transfer to you, so you have the original and not the fork?

**Comment by MatusGoljerSalesChamp** [comment]
Hah, thanks, but I think I'll decline.  We have the repo under our organization and some tooling (ci, composer etc) depends on the location, so why fix what isn't broken :D

We are somehow related (through common employees?) to the DotBlue company, so maybe you know some of them and they transfered it to you?  I'm not sure either, I've been only working here for a bit over a month.

**Comment by TomasVotruba** [comment]
No problem :+1: 

Maybe I've forked it and they deleted it. Will try the same here.

**Comment by TomasVotruba** [comment]
Btw, if you really want to make great coding standard, combine it with PHP-CS-Fixer. It has around 80-100 great fixers ready to use. It is pain to combine them in CLI, but easy to use with [EasyCodingStandard](https://github.com/Symplify/EasyCodingStandard#1-create-configuration).

**Comment by MatusGoljerSalesChamp** [comment]
Oh, that looks handy!  I'll have a look.

Also the fuzzy searcher for neon seems like a good idea, I'll add that to my [Emacs plugin](https://github.com/Fuco1/neon-mode) for neon :)

**Pull request closed without merging**
